package net.typeblog.socks.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors — Monochrome (black & white); green/red reserved for status only
val LightPrimary = Color(0xFF000000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF5F5F5)
val LightOnPrimaryContainer = Color(0xFF000000)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF5F5F5)
val LightSurfaceTint = Color(0xFFF5F5F5)
val LightOutline = Color(0xFFE5E5E5)
val LightOutlineVariant = Color(0xFFEEEEEE)
val LightOnSurface = Color(0xFF000000)
val LightOnSurfaceVariant = Color(0xFF555555)
val LightTertiary = Color(0xFF16A34A)
val LightError = Color(0xFFDC2626)
val LightSurfaceContainerLow = Color(0xFFFFFFFF)
val LightSurfaceContainerHighest = Color(0xFFF5F5F5)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF000000)
val LightOrangeSecondary = Color(0xFF000000)
val LightOrangeAccent = Color(0xFF000000)

// Dark Theme Colors — Monochrome (black & white); green/red reserved for status only
val DarkPrimary = Color(0xFFFFFFFF)
val DarkOnPrimary = Color(0xFF000000)
val DarkPrimaryContainer = Color(0xFF1A1A1A)
val DarkOnPrimaryContainer = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF0A0A0A)
val DarkSurfaceVariant = Color(0xFF1A1A1A)
val DarkSurfaceTint = Color(0xFF1A1A1A)
val DarkOutline = Color(0xFF2A2A2A)
val DarkOutlineVariant = Color(0xFF222222)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkOnSurfaceVariant = Color(0xFFAAAAAA)
val DarkTertiary = Color(0xFF22C55E)
val DarkError = Color(0xFFEF4444)
val DarkSurfaceContainerLow = Color(0xFF0A0A0A)
val DarkSurfaceContainerHighest = Color(0xFF1A1A1A)
val DarkBackground = Color(0xFF0A0A0A)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkOrangeSecondary = Color(0xFFFFFFFF)
val DarkOrangeAccent = Color(0xFFFFFFFF)
