package net.typeblog.socks.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors — Proton palette
val LightPrimary = Color(0xFF6D4AFF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFC7BAF1)
val LightOnPrimaryContainer = Color(0xFF0C0C14)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF5F4F2)
val LightSurfaceTint = Color(0xFFF5F4F2)
val LightOutline = Color(0xFFEAE7E4)
val LightOutlineVariant = Color(0xFFE0DDD9)
val LightOnSurface = Color(0xFF0C0C14)
val LightOnSurfaceVariant = Color(0xFF706D6B)
val LightTertiary = Color(0xFF1C9C7C)
val LightError = Color(0xFFCC2D4F)
val LightSurfaceContainerLow = Color(0xFFF5F4F2)
val LightSurfaceContainerHighest = Color(0xFFF1EEEB)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF0C0C14)
val LightOrangeSecondary = Color(0xFF6D4AFF)
val LightOrangeAccent = Color(0xFF6D4AFF)

// Dark Theme Colors — Proton palette
val DarkPrimary = Color(0xFF6D4AFF)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF292733)
val DarkOnPrimaryContainer = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF1C1B24)
val DarkSurfaceVariant = Color(0xFF292733)
val DarkSurfaceTint = Color(0xFF292733)
val DarkOutline = Color(0xFF3B3747)
val DarkOutlineVariant = Color(0xFF292733)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkOnSurfaceVariant = Color(0xFFA7A4B5)
val DarkTertiary = Color(0xFF2CFFCC)
val DarkError = Color(0xFFF08FA4)
val DarkSurfaceContainerLow = Color(0xFF1C1B24)
val DarkSurfaceContainerHighest = Color(0xFF292733)
val DarkBackground = Color(0xFF0C0C14)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkOrangeSecondary = Color(0xFF8A6EFF)
val DarkOrangeAccent = Color(0xFF8A6EFF)